### ISSUE TITLE
Possible error when calculating particles for localization initialization

### ISSUE THREAD

**Issue by romul90** [tier4/AutowareArchitectureProposal.iv#473]
Good day

I have a suspicion that there is an error during initialization of std::normal_distribution<> https://github.com/tier4/AutowareArchitectureProposal.iv/blob/8a1343019aca3a648754fa50e6cab72b98db2df5/localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/util_func.h#L247 

The variance value is used (from pose covariance matrix), not the standard deviation, as required by the documentation.  
Perhaps it should be done like this:  
`std::normal_distribution<> x_distribution(0.0, std::pow(base_pose_with_cov.pose.covariance[0], 0.5)); `

**Comment by YamatoAndo** [comment]
Thank you for your report!
As you say, the standard deviation should be used instead of the variance value.

Unfortunately AutowareArchitectureProposal.iv is rarely updated anymore, so your point may not apply.
However, I will fix it properly when AutowareArchitectureProposal.iv integrates into Autoware.Auto.

Thanks a lot!

**Comment by romul90** [comment]
@YamatoAndo Thank you for answer. I will close issue then.
